server:
  port: 9101

#服务名
spring:
  application:
    name: cloud-mybatisPlus9101 #服务名（多个实例可以共用一个服务名，服务寻址）

#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    #使用druid资源池
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

#mybatisplus配置
mybatis-plus:
  check-config-location: false
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      field-strategy: ignored #mybatisplus的字段策略（默认非null.即null的不生效）




