spring:
  #es配置
  #数据库配置
  datasource:
    url: jdbc:postgresql://localhost:5432/es_test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    #连接池
    hikari:
      maximum-pool-size: 10
  #jpa配置
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  main:
    allow-bean-definition-overriding: true
  elasticsearch:
    rest:
      uris: ["127.0.0.1:9200"]

elasticsearch:
  url: 127.0.0.1:9200
