spring:
  datasource:
    driver-class-name: com.kingbase8.Driver
#    url: jdbc:kingbase://127.0.0.1:54321/test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    url: jdbc:kingbase8://127.0.0.1:54321/test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: system
    password: 123456
    druid:
      # 初始化大小，最小，最大
      initial-size: 10
      min-idle: 10
      max-active: 50
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #      validation-query: SELECT dummy FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      db-type: postgresql
      # 监控配置
      # Druid WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico
      # Druid StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 登录监控界面的用户名以及密码，登录url为localhost:8080/druid
        login-username: admin
        login-password: admin
        allow:
        deny:

server:
    port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.test.kingbasedemo.entity  #mapper.xml里就不需要写类的全路径了
  configuration:
    map-underscore-to-camel-case: true   #驼峰转换

logging:
  level:
    com.dc.kingbasedemo.mapper: info